### ISSUE TITLE
Passing protoc path from Bazel

### ISSUE THREAD

**Issue by liningpan** [rthomas/bazel-rust-protos#1]
The `protoc` binary is available through `rules_proto`. The `rules_proto` rule set provides the repository `@com_google_protobuf` and the protoc target, which uses precompiled binaries whenever possible. 

```starlark
cargo_build_script(
    name = "proto_build_script",
    srcs = ["build.rs"],
    build_script_env = {
         "PROTOC": "$(execpath @com_google_protobuf//:protoc)",
    },
    data = [":greeter_protos", "@com_google_protobuf//:protoc"],
    deps = ["//third_party:tonic_build"],
)
```

I can submit a PR if you want.

**Comment by rthomas** [comment]
A PR would be great, thanks!
